plugins {
    id 'java'
}

group = 'com.flyaway.presentshunt'
version = '1.3.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
    maven {
        name = "papermc"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven { url = "https://repo.extendedclip.com/content/repositories/placeholderapi/" }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:26.3.build.159-beta'
    compileOnly 'me.clip:placeholderapi:2.12.3'
}

tasks.jar {
    archiveBaseName.set("PresentsHunt")
}

tasks.processResources {
    filesMatching("plugin.yml") {
        expand(
                version: project.version,
                name: project.name,
                group: project.group
        )
    }
}
